parser: "@typescript-eslint/parser" # Specifies the ESLint parser
extends:
  - "plugin:@typescript-eslint/recommended" # Uses the recommended rules from the @typescript-eslint/eslint-plugin
  # - "prettier/@typescript-eslint"
parserOptions:
  ecmaVersion: 2018 # Allows for the parsing of modern ECMAScript features
  sourceType: "module" # Allows for the use of imports
rules:
  # Place to specify ESLint rules. Can be used to overwrite rules specified from the extended configs
  # spacing handled by prettier
  "@typescript-eslint/indent": "off"
  "@typescript-eslint/no-object-literal-type-assertion": "off"
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-use-before-define": "off"
env:
  node: true
  browser: false
overrides: []
